import fs from 'fs'
import {createRequire} from "module";
import {badge, image, link, visitorBadge} from "./helper/markdown-helper.js";
import {sortObjectsByColor} from "./helper/rainbow-helper.js";

const require = createRequire(import.meta.url);
const content = require("./content.json");

(async () => {
  let thingsIWorkWith = ''
  const thingsToCodeWith = sortObjectsByColor(content.thingsToCodeWith)
  for (let thingToCodeWith of thingsToCodeWith) {
    thingsIWorkWith += badge(thingToCodeWith.text, thingToCodeWith.logo, thingToCodeWith.colorObj.hex) + '\n'
  }

  const result = `<!-- This file is automatically generated. -->
![](./src/assets/header.png)

<table style="width: 100%; border: none;" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td>
<span style="font-size: 1.25rem;">Hello <img src="https://media.giphy.com/media/hvRJCLFzcasrR4ia7z/giphy.gif" alt="" width="20"></span>
<br><br>
I'm Stijn, full stack developer from <img alt="" height="13" src="https://cdn-icons-png.flaticon.com/512/197/197441.png" width="13"/> <strong>The Netherlands</strong>.<br>
I like to work on random projects in my spare time and want to discover more and more new things over time. I also like to listen to music while working and have an addiction to watching things on YouTube.
<br><br><br>
${badge('stijn-van-nieulande', 'linkedin', '2d2c2e', 'https://www.linkedin.com/in/stijn-van-nieulande-95b248a2/', true)}
${badge('website', null, '2d2c2e', 'https://stijn.dev/', true)}
${visitorBadge('Stijn-van-Nieulande.Stijn-van-Nieulande', true)}
</td>
<td width="320">
<a href="https://github.com/kittinan/spotify-github-profile"><img src="${content.spotifyImageUrl}" alt=""></a>
</td>
</tr>
</tbody>
</table>

### <img alt="" height="30" src="https://cdn-icons-png.flaticon.com/512/1055/1055683.png" width="30"/>&nbsp;&nbsp; Technologies and tools i'm using
${thingsIWorkWith}

### <img alt="" height="30" src="https://cdn-icons-png.flaticon.com/512/1387/1387817.png" width="30"/>&nbsp;&nbsp; My GitHub statistics
<small>**Note:** Most statistics are just a metric made up of my public code and not a reflection of experience or skill level.</small>

${image('Stats', content.statisticsImageUrl)}

<details>
<summary>More GitHub statistics</summary>

${link(image('GitHub Streak', content.githubStreakImageUrl), 'https://git.io/streak-stats')}
${image('Most Used Languages', content.topLanguagesImageUrl)}

${image('Activity', content.activityImageUrl)}
</details>

${link(image('Trophies', content.trophiesImageUrl), 'https://github.com/ryo-ma/github-profile-trophy')}
`

  fs.writeFile("README.md", result, err => {
    if (err) return console.log(err)
    console.log('Successfully wrote result to readme', result)
  })
})()
